default_platform(:android)

platform :android do

  desc 'Deploy a new internal version to the Google Play Store'
  lane :deploy do
    supply(
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      track: 'internal'
    )
  end

end
