dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  flutter_state_notifier: ^0.7.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.18.0
  state_notifier: ^0.7.2
dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
environment:
  sdk: '>=2.18.5 <3.0.0'
flutter:
  assets:
  - assets/config/config.json
  uses-material-design: true
flutter_icons:
  android: launcher_icon
  image_path: assets/app_icon.png
  ios: true
flutter_native_splash:
  color: '#ff8000'
  image: assets/launch_app.png
name: mathiflo
publish_to: none
version: 1.0.0+18
