dependencies:
  cupertino_icons: ^1.0.5
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_state_notifier: ^0.7.3
  http: ^0.13.5
  intl: ^0.18.0
  localstore: ^1.3.5
  state_notifier: ^0.7.2+1
  vibration: ^1.7.6
dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.18.5 <3.0.0'
flutter:
  assets:
  - assets/config/config.json
  uses-material-design: true
flutter_icons:
  android: launcher_icon
  image_path: assets/app_icon.png
  ios: true
flutter_native_splash:
  color: '#ffffff'
  image: assets/launch_app.png
name: mathiflo
publish_to: none
version: 1.0.0+26
